#!/bin/csh -f

#set ROOTSYS = "/virgo/ext/root/root_v5.14.00/Linux-x86_64-SL5"
if ( $?ROOTSYS == 0 ) then
  echo "ROOTSYS is undefined"
  exit
endif

#------------------------------------------------------------------------------
if ( $?UNAME == 0 ) then
  setenv UNAME `uname`
endif
if( $UNAME == "Linux" ) then
  setenv UNAME `uname`-`uname -m`
endif
echo " -------> This is $UNAME <--- ROOTSYS is $ROOTSYS "
mkdir ../$UNAME  
cd ../$UNAME

rm -f *.o

echo "----------------------------------------Compile Fr code"
# _USE_CPP11
set CXXGENFL = "-O -fPIC  -fno-exceptions" 



gcc  $CXXGENFL -I../src -I../src/zlib -c ../src/FrIO.c
gcc  $CXXGENFL -I../src -I../src/zlib -c ../src/FrameL.c 
gcc  $CXXGENFL -I../src -I../src/zlib -c ../src/FrFilter.c
gcc  $CXXGENFL -I../src -I../src/zlib -c ../src/zlib/*.c 

#rootcint
echo "-----------------------------------------------Run CINT" 
rootcling -f G_frameL.C -c -I../src/ -D__cplusplus ../src/FrameL.h  ../root/FrRootLinkDef.h
#

echo "------------------------------------compile CINT output"
g++ -DG__REGEXP -DG__SHAREDLIB -DG__OSFDLL --std=c++11 $CXXGENFL -I$ROOTSYS/include -I$ROOTSYS/include/root -I../src -c G_frameL.C
# for 

echo "----------------------------- build ROOT Shared Library"
gcc   -fno-common -dynamiclib -undefined dynamic_lookup -o libFrameROOT.dylib *.o 

echo "------------------------------------------------cleanup"
rm -f *.o
rm -f G_frameL.*
    
